AWSTemplateFormatVersion: "2010-09-09"
Description: "Collect findings from security hub and notify them to SNS topic."

Resources:
  SlackNotificationTopic:
    Type: "AWS::SNS::Topic"
  SlackNotificationTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      Topics:
        - !Ref SlackNotificationTopic
      PolicyDocument:
        Version: "2012-10-17"
        Id: "__default_policy_ID"
        Statement:
          - Sid: "__default_statement_ID"
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action:
              - "SNS:GetTopicAttributes"
              - "SNS:SetTopicAttributes"
              - "SNS:AddPermission"
              - "SNS:RemovePermission"
              - "SNS:DeleteTopic"
              - "SNS:Subscribe"
              - "SNS:ListSubscriptionsByTopic"
              - "SNS:Publish"
              - "SNS:Receive"
            Resource: !Ref SlackNotificationTopic
            Condition:
              StringEquals:
                AWS:SourceOwner: !Ref AWS::AccountId
          - Sid: "Allow_Publish_Events"
            Effect: "Allow"
            Principal:
              Service: "events.amazonaws.com"
            Action: "sns:Publish"
            Resource: !Ref SlackNotificationTopic
  CloudWatchEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Name: !Ref AWS::StackName
      Description: "Receive security hub findings and pass them to SNS topic."
      EventPattern:
        source:
          - "aws.securityhub"
        detail-type:
          - "Security Hub Findings - Imported"
        detail:
          findings:
            ProductFields:
              aws/securityhub/SeverityLabel:
                - CRITICAL
                - HIGH
                - MEDIUM
      Targets:
        - Arn: !Ref SlackNotificationTopic
          Id: Id1
